### ISSUE TITLE
"Build your own devon4j application" links to TeamForge Download site with outdated devonfw distribution

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/jump-the-queue#18]
Category: Bug

Severity: High

Expected behaviour (In case of bug)
All links that are intended for downloading the latest version of devonfw should point to a download location that serves the latest version

Actual/current behaviour (In case of bug)
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application#creating-components there is a link to TeamForge (https://coconet.capgemini.com/sf/frs/do/listReleases/projects.apps2_devon/frs.devon_distribution) that appears to be outdated - the newest version available there is 2.4.0
> You can download devonfw distributions from TeamForge.

Steps to reproduce (In case of bug)
Klick on "TeamForge" on https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application#creating-components

Description of issue / expected enhacement /Comments
The Link must point to the download loacation with the newest devonfw releases

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by phschimm** [comment]
All links on this page are now working.
