### ISSUE TITLE
devon4j installation instructions should make a note on patching

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/jump-the-queue#20]
Category: enhancement

Severity: Low

Description of issue / expected enhacement /Comments
The instructions how to install devonfw distribution on https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4j-application tell the user how to unzip the distribution and - in the next step - how to initialize it using update-all-workspaces.bat. After that, the instructions tell the user to start developing.
The instructions should tell the user to look for patches (e.g. win_accumulative_patch_20190115.zip) that should be applied to the distribution before starting to develop.

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by phschimm** [comment]
With the new IDE that we are now linking it's not necessary to update workspaces manually anymore.
