### ISSUE TITLE
Creating a new application with devcon doesn't work as described and leaves open questions

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/jump-the-queue#21]
Category: Bug

Severity: Medium

Expected behaviour (In case of bug)
The steps as described in the instructions to create a new application result in a newly created project and the user of the tutorial has learned how to create a new project. 

Actual/current behaviour (In case of bug)
The steps as described in the instructions to create a new application are not sufficient and leave open questions

Steps to reproduce (In case of bug)
follow the instructions on https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4j-application:
> Then we only need to define our server app path (for the location of the app select our just created jumpthequeue directory), name, groupid, package and version. Finally click on Start button.

Description of issue / expected enhacement /Comments
- there is no field "name" but two fields "servername" and "packagename"
- it is unclear, what "name" or "servername" actually is (it probably is the maven artifactID or is it some devonfw-specific name???)
- it should be mentioned that these parameters are filled in the maven pom (and the meaning of these parameters can be found in any documentation on maven). 
- explicitly give the values "jtqj", "com.defonfw.application.jtqj", "v4" and "h2" for the fields to be filled in this tutorial.
- it *must* be mentioned that also the dbtype has to be given - and should be "h2" for this development.

by the way: there is a bug in devcon that results in a lock-up if you forget to provide all mandatory values. You have to get back and start creating the project from scratch - re-filling all fields again. 

Your environment - windows/Linux, Devonfw version , component
windows

**Comment by phschimm** [comment]
This part of the tutorial has now been adapted for use with the new devonfw IDE and should work properly. The new CLI now defaults to the H2 DB scheme when creating a new project. We are now also mentioning the `pom.xml` and linking to the official Maven page, so readers can inform themselves.

https://github.com/devonfw/jump-the-queue/wiki/build-devon4j-application#creating-the-project
