### ISSUE TITLE
Misleading Cobigen value for AccessCode component

### ISSUE THREAD

**Issue by Sroooooka** [devonfw/jump-the-queue#30]
Category: Bug

Severity: High

In chapter [Devon4J components](https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-components) when using settings like on [screen](https://raw.githubusercontent.com/wiki/devonfw/devonfw-tutorial-sources/images/devon4j/4.Components/cobigen3_allpackages_cto.png) I receive multiple errors. Errors can be fixed when selecting option "TO's" when generating AccessCode component structure with CobiGen.

**Comment by phschimm** [comment]
Thank you for reporting this issue.
The documentation now reflects this correctly.
